### ISSUE TITLE
OSError: SavedModel file does not exist at: /home/riki/Desktop/TelloVision/C:\Users\Ofek\Desktop\coding\TelloVision/{saved_model.pbtxt|saved_model.pb} terminate called without an active exception

### ISSUE THREAD

**Issue by zzb1967736495** [Kafow/TelloVision#4]
OSError: SavedModel file does not exist at: /home/riki/Desktop/TelloVision/C:\Users\Ofek\Desktop\coding\TelloVision/{saved_model.pbtxt|saved_model.pb}
terminate called without an active exception

**Comment by Kafow** [comment]
Hey, you need to change the constant to match your local file.
